---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "Standalone Linting"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - "*"
      - "!update-devops-tooling"

jobs:
  linting:
    name: "MyPy"
    runs-on: "ubuntu-latest"
    # Don't run when pull request is merged
    if: github.event.pull_request.merged == false

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Patch linting configuration"
        run: |
          # Patch the linting configuration
          # This step prevents a bunch of tools being installed
          # (which substantically increases workflow execution time)
          mv .pre-commit-config.yaml .pre-commit-config.yaml.previous
          cat << 'EOF' > .pre-commit-config.yaml
          ---
          # SPDX-License-Identifier: Apache-2.0
          # SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

          ci:
            autofix_commit_msg: "Chore: pre-commit autoupdate"

          exclude: |
            (?x)^(
                docs\/conf.py|
                dco-signoffs/$
            )$

          repos:
            - repo: local
              hooks:
                - id: mypy-cache
                  name: "create mypy cache"
                  language: system
                  pass_filenames: false
                  entry: bash -c 'if [ ! -d .mypy_cache ]; then /bin/mkdir .mypy_cache; fi; exit 0'

            - repo: https://github.com/pre-commit/mirrors-mypy
              rev: "v1.11.0"
              hooks:
                - id: mypy
                  verbose: true
                  args: ["--show-error-codes", "--install-types", "--non-interactive"]
                  additional_dependencies: ["pytest", "types-requests"]
          EOF

      - name: "Install linting dependencies"
        run: |
          # Install linting dependencies
          pip install --upgrade pip
          pip install pre-commit mypy

      - name: "Run MyPy with Pre-commit"
        run: |
          # Run MyPy with Pre-commit
          if [ ! -d .mypy_cache ]; then /bin/mkdir .mypy_cache; fi
          pre-commit run mypy -a

        # yamllint disable rule:line-length
        # yamllint disable rule:comments-indentation
        # yamllint disable rule:comments

        # Provided below as an example, in case needed in future
        # - name: "Install dependencies"
        #   run: |
        #     SOURCE=".pre-commit-config.yaml"
        #     echo "Install Python dependencies from: $SOURCE"
        #     echo "With: pip install $PKGS"
        #     PKGS=$(yq '.repos[] | select (.repo == "https://github.com/pre-commit/mirrors-mypy")' .pre-commit-config.yaml | \
        #       grep additional_dependencies | \
        #       awk -F: '{print $2}' | \
        #       sed "s/\[//g" | \
        #       sed "s/\]//g" | \
        #       sed "s/,//g" | \
        #       sed 's/"//g')
        #       pip install $PKGS
